### ISSUE TITLE
Don't render text centered

### ISSUE THREAD

**Issue by Ryuno-Ki** [alwayslivid/eleventy-about-me#6]
I know, it looks cool and so on.
But after checking the screenshot after #5 I noticed, that the text is centered.
This way [text will be harder to read](https://practicaltypography.com/centered-text.html) and that's the least you would want on a business-card ;-)

**Comment by alwayslivid** [comment]
This was meant to be a deliberate design choice, however, you're correct on the readability part.

I will try to experiment with `justify` instead of `center` tomorrow. If that succeeds, then I'll push the changes.

The container is centered anyways, so taking advantage of all the space that's available would be great, and frankly, I did feel like something didn't quite sink in properly with my template.

**Comment by alwayslivid** [comment]
I tried enhancing the layout, so that it'd use `center` on portrait mode and `justify` on landscape mode.

It works great, but my primary concern is that `justify` is just going to look weird under specific circumstances:

![image](https://user-images.githubusercontent.com/30193966/56810429-f3429980-683e-11e9-88c6-649ea30d17c5.png)

It would be definitely possible to just align all the contents to the left on landscape mode, but I feel like that such a move would drift too much away from the original concept of the template, and the different alignment between desktop and mobile devices feels kind of weird *(but that's probably me, this modified version would probably look amazing with a proper header picture, not going to lie.)*

![image](https://user-images.githubusercontent.com/30193966/56810792-d3f83c00-683f-11e9-8eee-401714895921.png)

Here's the code that I used to make those previews, for the sake of posterity;

```css
@media screen and (orientation: landscape) {
	.box {
		width: 40%
	}
	.content, h1, h2, h3, h4, h5, h6 {
		text-align: justify
	}
	.icon {
		display: block;
		margin-left: auto;
		margin-right: auto;
	}
}

@media screen and (orientation: portrait) {
	.box {
		width: 70%;
	}
	.content, h1, h2, h3, h4, h5, h6 {
		text-align: center;
	}
}
```
